name: bip47
description: Basic bip47 implementation with Samourai segwit
version: 2.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  bitcoindart:
    git:
      url: https://github.com/cypherstack/bitcoindart.git
      ref: 7145be16bb88cffbd53326f7fa4570e414be09e4
  bip39:
    git:
      url: https://github.com/cypherstack/stack-bip39.git
      ref: 20bc8ca0bf0a30c6965977a26c41475a9e862020
  pointycastle: ^4.0.0
  convert: ^3.0.2
  bip32:
    git:
      url: https://github.com/cypherstack/bip32-dart
      ref: 9a7e9b9bad9872c69dd1383d6b2e6090f85148fc
  hex: ^0.2.0
  dart_bs58: ^1.0.1
  dart_bs58check:
    git:
      url: https://github.com/cypherstack/dart-bs58check
      ref: bed60e43e4e509ea45bb097e6caee9f8293ddf98
#  http: ^0.13.5